### ISSUE TITLE
执行最后一步编译的时候报错

### ISSUE THREAD

**Issue by haofeng0705** [wangzt-halo/das#1]
<img width="1125" alt="image" src="https://user-images.githubusercontent.com/30925823/189597618-70cf4a55-59ba-4b10-9456-8425666303c6.png">

**Comment by a2394797795** [comment]
这个应该是pytorch版本和mmdet版本的兼容问题，用1.10以下的pytorch就可以了

**Comment by wangzt-halo** [comment]
这个应该是pytorch版本和mmdet版本的兼容问题，用pytorch 1.10以下应该就行

**Comment by Elliot-hao** [comment]
<img width="463" alt="image" src="https://user-images.githubusercontent.com/30925823/190996398-9bdcc0d3-cedc-4ab8-85bc-626f417e1de2.png">
请问大大这数据集下完是这样吗

**Comment by haofeng0705** [comment]
解决了，大大请问CMU 数据是只用下载 readme 中那些 hdvideo（10 个）是吧？

**Comment by wangzt-halo** [comment]
下载训练集和验证集的这些[视频](https://github.com/wangzt-halo/das/blob/c729703dbab31b7ea8d3a18245f9c3dd4513225b/mytools/panoptic2coco.py#L13)就行

**Comment by haofeng0705** [comment]
谢谢
