### ISSUE TITLE
About Reimplementation

### ISSUE THREAD

**Issue by JohnW2all** [wangzt-halo/das#12]
**Issues**
I try to reimplement the original model using the provided configs _exp_panoptic.py_ but could not reach the performance described in the paper and loss fell slowly.
Under the same training configuration, according to the training log you provided, the loss at the end of the epoch 1 was around 5, while my loss was 13. At the end of the epoch 22,  your loss was -3 and mine was 7. 
Meanwhile, the performance was also quite different when tested on the four subdatasets of panoptic.
Epoch1:
![image](https://github.com/wangzt-halo/das/assets/75520758/ab568f50-6814-4be3-a7c0-011d7e6a2623)
Epoch22:
![image](https://github.com/wangzt-halo/das/assets/75520758/cfa55fa9-c649-4e66-8256-aeaadf1c72d6)

**Command**
![image](https://github.com/wangzt-halo/das/assets/75520758/60e9509c-f260-4677-bb2c-3454dfc231ee)

**Config**
Provided _exp_panoptic.py_

**Environment**
![image](https://github.com/wangzt-halo/das/assets/75520758/01929445-a537-4155-895e-793495820979)

Looking forward to your reply.
Thanks a lot!

**Comment by wangzt-halo** [comment]
Can you provide me with the log file?
We used 4 gpus for distributed training, and this might be the reason for the performance difference.

**Comment by JohnW2all** [comment]
十分感谢您的回复！
由于分布式训练需要修改代码，之前捣鼓了几天但是没有成功，所以一直使用单GPU进行训练的。像您说的可能这就是问题所在。我的训练日志删除了，我重新训练一下再发给您。
此外，我想请问一下是否必须使用多gpu训练才可以达到您论文中的性能呢？如果是的话该修改代码的那些部分才可以实现分布式训练呢？
不胜感激！

补充：github提问好像不能传文件，log文件我明日会在发您的邮箱（我的邮箱用户名为“陈潇”），十分感谢！

**Comment by wangzt-halo** [comment]
这份代码基于mmdetection，是自带分布式训练的，你可以试试这个命令
`bash tools/dist_train.py configs/das/exp_panoptic.py 4`

**Comment by JohnW2all** [comment]
十分感谢您的回复！现在成功运行了。
我之前也使用过这个命令但是没有成功，当时误以为需要修改代码，其实是服务器内存不足。
十分感谢！

![image](https://github.com/wangzt-halo/das/assets/75520758/464110be-5382-4068-85a0-399375b10ef8)

**Comment by JohnW2all** [comment]
老师您好，我使用分布式训练后发现还是没能解决之前的问题。发现数据集的问题可能是导致我复现失败的原因。
我在使用panoptic2coco.py处理panoptic数据集时有如下问题：
![image](https://github.com/wangzt-halo/das/assets/75520758/dd9cdfd4-ae0d-4a4d-862e-eb5552da1eac)
产生该问题的原因是子数据集mafia和ultimatum的内容不全（下载使用的是panoptic官方代码https://github.com/CMU-Perceptual-Computing-Lab/panoptic-toolbox）。
所有mafia数据集和部分ultimatum数据集没有hdPose3d_stage1_coco19文件夹（而haggling数据集和pizza数据集都有该文件夹）：

数据集文件：
![image](https://github.com/wangzt-halo/das/assets/75520758/5ca64c2d-2c8b-4c38-8f58-5c8ac65a960f)
haggling数据集都有这些文件：
![image](https://github.com/wangzt-halo/das/assets/75520758/64e1b864-a3fd-4f0f-8a3b-d5cafdaa75e8)
mafia数据集和ultimatum数据集缺少hdPose3d_stage1_coco19文件夹：
![image](https://github.com/wangzt-halo/das/assets/75520758/6c15870c-bba9-4e75-aa07-e68383565b26)
![image](https://github.com/wangzt-halo/das/assets/75520758/10eb716c-b27a-406a-851d-a550716d1045)

由于mafia数据集预处理失败无法生成mafia.json，这也导致我无法在mafia数据集上进行测试
![image](https://github.com/wangzt-halo/das/assets/75520758/521d22ab-28bc-4f6a-bbd0-f3af47dc1f7c)


我想请问一下您是否可以提供mafia和ultimatum数据集中缺少的对应的hdPose3d_stage1_coco19文件。谢谢！

**Comment by wangzt-halo** [comment]
有些序列是缺少`hdPose3d_stage1_coco19`标注文件的，在这些序列里我们使用的是`hdPose3d_stage1`标注，你可以下载后者

**Comment by JohnW2all** [comment]
hdPose3d_stage1标注

**Comment by JohnW2all** [comment]
感谢回复。我想请问hdPose3d_stage1标注应该如何下载呢？我暂时没有找到下载方法。
![image](https://github.com/wangzt-halo/das/assets/75520758/a2cdcbcc-9058-41b3-bb0f-6ae7bd992efe)
