### ISSUE TITLE
About develop environment

### ISSUE THREAD

**Issue by henrycjh** [wangzt-halo/das#4]
Could you please provide your develop environment？ Like OS，version of pytorch，python and etc..
I got a lot of errors, and it's all about conflicts between versions of packages when running setup.py.

**Comment by EileenWang90** [comment]
The author provided the training log in [Google Cloud Drive](https://drive.google.com/drive/folders/1zQ_eS59lBtyPdq9pOFnk4AgWVUiphLbl), which has some environment details. It may help.
